upload_source_maps = true

name = "sink"
type = "javascript" # or "webpack" if you are using Webpack

account_id = "ded52c6834df99f0ff92fae2e0596239"
workers_dev = true

# KV Namespace bindings
kv_namespaces = [
  { binding = "sink-binding", id = "00cbe1f58fb64fd9a0089bdd74742c96" }
]

# Optional: Additional configuration settings
# compatibility_date = "2024-07-27"
# usage_model = "bundled" # or "unbound"

[dev]
port = 3000

[ai]
binding = "AI"

# Add new configuration settings
zone_id = "ae5f1b3510f89ae726a7e5a4f777d9f1"
route = "volgamo.com/*"

[env.production]
account_id = "ded52c6834df99f0ff92fae2e0596239"
zone_id = "ae5f1b3510f89ae726a7e5a4f777d9f1"
route = "volgamo.com/*"

[build]
command = "npm run build"
