upload_source_maps = true

name = "sink"
type = "javascript" # or "webpack" if you are using Webpack

account_id = "ded52c6834df99f0ff92fae2e0596239"
workers_dev = true

# KV Namespace bindings
kv_namespaces = [
  { binding = "sink-binding", id = "00cbe1f58fb64fd9a0089bdd74742c96" }
]

# Optional: Additional configuration settings
# compatibility_date = "2024-07-27"
# usage_model = "bundled" # or "unbound"

[dev]
port = 3000

[ai]
binding = "AI"
